version: 3

tasks:
  s3-explorer:
    dotenv:
      - .secrets/s3.env
    silent: true
    cmds:
      - |+
        chmod 600 .secrets/s3.access

        mkdir -p /tmp/s3-explorer
        s3fs $S3_BUCKET_NAME /tmp/s3-explorer $S3FS_FLAGS -o passwd_file=.secrets/s3.access

        ranger /tmp/s3-explorer

  k3s-etcd:
    dir: ./k3s-etcd
    requires:
      vars:
        - image
    cmds:
      - |+
        sudo rm -rf ./.result ./.result.d ./.nix-closure

        # nix build .#k3s-etcd -o .result

        mkdir -p .nix-closure
        sudo cp -r $(nix-store -qR .result) .nix-closure

        mkdir -p .result.d
        [ -d .result/bin ] && cp -r .result/bin .result.d/
        [ -d .result/lib ] && cp -r .result/lib .result.d/

        docker buildx build --output=type=image,compression=zstd,force-compression=true,compression-level=12,push=true -t {{.image}} .

  mongodb-backup:
    dir: ./mongodb
    requires:
      vars:
        - image
    cmds:
      - |+
        sudo rm -rf ./.result ./.result.d ./.nix-closure

        nix build .#mongodb-backup -o .result

        mkdir -p .nix-closure
        # sudo cp -r -p $(nix-store -qR .result) .nix-closure
        cp -r $(nix-store -qR .result) .nix-closure

        mkdir -p .result.d
        [ -d .result/bin ] && cp -R .result/bin .result.d/
        [ -d .result/lib ] && cp -R .result/lib .result.d/

        docker buildx build --output=type=image,compression=zstd,force-compression=true,compression-level=12,push=true -t {{.image}} .

  nats-backup:
    dir: ./nats
    requires:
      vars:
        - image
    cmds:
      - |+
        sudo rm -rf ./.result ./.result.d ./.nix-closure

        nix build .#nats-backup -o .result

        mkdir -p .nix-closure
        sudo cp -R $(nix-store -qR .result) .nix-closure

        mkdir -p .result.d
        [ -d .result/bin ] && cp -R .result/bin .result.d/
        [ -d .result/lib ] && cp -R .result/lib .result.d/

        docker buildx build --output=type=image,compression=zstd,force-compression=true,compression-level=12,push=true -t {{.image}} .
